Web design Python dengan framework Django/blog/urls.py
from django.conf.urls import url
from django.conf.urls import include

from . import views

urlpatterns = [
	url(r'^$', views.index, name="index"),
	url(r'^post/(?P<slugInput>[\w-]+)/$', views.detailPost, name="detail"),
	url(r'^category/(?P<categoryInput>[\w-]+)/$', views.categoryPost, name="category"),
]

Web design Python dengan framework Django/mywebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from . import views

urlpatterns = [
	url(r'^$', views.index, name = "index"),
	url(r'^blog/',include('blog.urls', namespace="blog")),
	url(r'^tinymce/', include('tinymce.urls')),
    url(r'^admin/',admin.site.urls),
]

Web design Python dengan framework Django/blog/models.py
from django.db import models
from django.utils.text import slugify


# Create your models here.

class Post(models.Model):
	judul		= models.CharField(max_length=255)
	body		= models.TextField()
	category	= models.CharField(max_length=255)
	publish		= models.DateTimeField(auto_now_add = True)
	update		= models.DateTimeField(auto_now = True)
	slug		= models.SlugField(blank=True, editable = False)


	def save(self):
		self.slug = slugify(self.judul)
		super(Post, self).save()

	def __str__(self):
		return "{}. {}".format(self.id,self.judul)

Web design Python dengan framework Django/blog/views.py
from django.shortcuts import render

# Create your views here.

from .models import Post

def index(request):
	posts = Post.objects.all();
	categories = Post.objects.values('category').distinct();
	context = {
		'Judul':'Home Blog',
		'Content':'.',
		'Categories':categories,
		'Posts':posts,
	}

	return render(request,'blog/index.html',context)

def categoryPost(request,categoryInput):
	posts = Post.objects.filter(category=categoryInput);
	categories = Post.objects.values('category').distinct();
	context = {
		'Judul':'Home Blog',
		'Content':'tampilkan berdasarkan category',
		'Categories':categories,
		'Posts':posts,
	}

	return render(request,'blog/category.html',context)


def detailPost(request,slugInput):
	posts = Post.objects.get(slug=slugInput);
	categories = Post.objects.values('category').distinct();
	context = {
		'Judul':'Home Blog',
		'Content':'ini adalah halaman blog',
		'Categories':categories,
		'Posts':posts,
	}

	return render(request,'blog/detail.html',context)

Web design Python dengan framework Django/mywebsite/views.py
from django.shortcuts import render


def index(request):
	context = {
		'Judul':'Home Page',
		'Content':'ini adalah home page dari website ini'
	}

	return render(request,'index.html',context)

Web design Python dengan framework Django/blog/templates/blog/category-post.html
{% extends "base.html" %}

{% block Title %}
	Blog Web Python
{% endblock Title %}

{% block pageTitle %}
	Blog Web Python
{% endblock pageTitle %}

{% block pageSubTitle %}
	Selamat membaca
{% endblock pageSubTitle %}

{% block contents %}
	<p>Kategori: 
		<ul class="nav">
			<li class="nav-item">
				<a class="nav-link" href="/blog">
					all-post
				</a>
			</li>

		{% for category in Categories %}
			<li class="nav-item">
				
				<a class="nav-link" href="../{{category.category}}">{{category.category}}</a>

			</li>
		{% endfor %}
		</ul>
	</p>

	<p>Semua post di kategori : {{Content}}</p>

	{% for post in Posts %}
		<a href="/blog/post/{{post.slug}}"><h1>{{post.judul}}</h1></a>
		<p>{{post.publish}}</p>
		<p>{{post.body | truncatechars:200}}</p>
	{% endfor %}
{% endblock contents %}

Web design Python dengan framework Django/blog/templates/blog/category.html
{% extends "base.html" %}

{% block Title %}
	{{Judul}}
{% endblock Title %}


{% block pageTitle %}
	{{Judul}}
{% endblock pageTitle %}

{% block contents %}
	{{Content}}
	<ul class="nav">

		<li class="nav-item">
			<a class = "nav-link" href="/blog" title="">
				All-post	
			</a>
			
		</li>

	{% for dataCategory in Categories %}
		<li class="nav-item">
			<a class = "nav-link" href="/blog/category/{{dataCategory.category}}" title="">
				{{dataCategory.category}}	
			</a>
			
		</li>
	{% endfor %}
	</ul>

	{% for post in Posts %}
		<a href="/blog/post/{{post.slug}}" title="">
			<h1>{{post.judul}}</h1>
		</a>
		<p>{{post.publish}}</p>
		<p>{{post.body|truncatechars:200}}</p>
	{% endfor %}
	

{% endblock contents %}

Web design Python dengan framework Django/blog/templates/blog/detail.html
{% extends "base.html" %}
{{post.content|safe}}
{% block Title %}
	{{Judul}}
{% endblock Title %}


{% block pageTitle %}
	{{Judul}}
{% endblock pageTitle %}

{% block contents %}
	{{Content}}

	<ul class="nav">

		<li class="nav-item">
			<a class = "nav-link" href="/blog" title="">
				All-post	
			</a>
			
		</li>

	{% for dataCategory in Categories %}
		<li class="nav-item">
			<a class = "nav-link" href="/blog/category/{{dataCategory.category}}" title="">
				{{dataCategory.category}}	
			</a>
			
		</li>
	{% endfor %}
	</ul>

	<h1>{{Posts.judul}}</h1>
	<p>{{Posts.publish}}</p>
	<p>{{Posts.body}}</p>

{% endblock contents %}

Web design Python dengan framework Django/blog/templates/blog/index.html
{% extends "base.html" %}



{% block Title %}
	{{Judul}}
{% endblock Title %}

{% block pageTitle %}
	{{Judul}}
{% endblock pageTitle %}


	<p></p>
{% block contents %}
	{{Content}}
	<ul class="nav">

		<li class="nav-item">
			<a class = "nav-link" href="{% url "blog:index" %}" title="">
				All-post	
			</a>
			
		</li>

	{% for dataCategory in Categories %}
		<li class="nav-item">
			<a class = "nav-link" href="{% url "blog:category" categoryInput=dataCategory.category%}" title="">
				{{dataCategory.category}}	
			</a>
			
		</li>
	{% endfor %}
	</ul>
	{% for post in Posts %}
		<a href="{% url "blog:detail" slugInput=post.slug %}" title="">
			<h1>{{post.judul}}</h1>
		</a>
		<p>{{post.publish}}</p>
		<p>{{post.body|truncatechars:200}}</p>
	{% endfor %}
{% endblock contents %}

Web design Python dengan framework Django/blog/templates/blog/single-post.html
{% extends "base.html" %}

{% block Title %}
	Blog-Web Python
{% endblock Title %}

{% block pageTitle %}
	Blog Web Python
{% endblock pageTitle %}

{% block pageSubTitle %}
	Selamat membaca
{% endblock pageSubTitle %}
<script src="{% static "js/tinymce/tinymce.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/tinymce/custom.js" %}" ></script>
{% block contents %}
	<p>{{ form.as_p }}Kategori: 
		<ul class="nav">
			<li class="nav-item">
				<a class="nav-link" href="/blog">
					all-post
				</a>
			</li>
		{% for category in Categories %}
			<li class="nav-item">
				
				<a class="nav-link" href="/blog/{{category.category}}">{{category.category}}</a>

			</li>
		{% endfor %}
		</ul>
	</p>

	<h1>{{Posts.judul}}</h1>
	<h6>Kategori: {{Posts.category}}</h6>
	<h5>ditulis: {{Posts.publish}}</h5>
	<br>
	<p>{{Posts.body}}</p>
{% endblock contents %}

Web design Python dengan framework Django/templates/base.html
{% load static %}
{{post.content|safe}}
<!DOCTYPE html>
<html>
<head>

	<title>
		{% block Title %}
		
		{% endblock Title %}
	</title>
	<!--Tinymce Text-Editor (Must be in Head Tag) -->
  	<script src="{% static "js/tinymce/tinymce.min.js" %}"></script>
  	<script type="text/javascript" src="{% static "js/tinymce/custom.js" %}" ></script>
	{% include "snippets/styles.html" %}

</head>
<body>
	{{post.content|safe}}
	{% include "snippets/navbar.html" %}
	<div class="container" style="margin-top:150 px">
		<h1>
		{% block pageTitle %}
			
		{% endblock pageTitle %}
		</h1>
	</div>
	
	<div class="container bg-light shadow mt-5">
		
		{% block contents %}
		
		{% endblock contents %}	
	</div>
	
	
	{% include "snippets/scripts.html" %}
</body>
</html>

Web design Python dengan framework Django/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link rel="stylesheet" type="text/css" href="{% static "vendor/bootstrap/bootstrap.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
</head>
<body>
	<nav class="navbar fixed-top navbar-expand-md navbar-dark" id="myNav">
	  <a class="navbar-brand" href="#">
	  		<img style="height:100px"src="{% static "img/Python-Transparent-Background.png" %}" alt="">
	  </a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav ml-auto">
	      	<li class="nav-item">
	      		<a class="nav-link" href="/" title="">Home</a>
	      	</li>
	      	<li class="nav-item">
	      		<a class="nav-link" href="/blog" title="">Blog</a>
	      	</li>
	      	<li class="nav-item">
	      		<a class="nav-link" href="admin/" title="">Admin</a>
	      	</li>
	    </ul>
	  </div>
	</nav>
	
	<div class="jumbotron jumbotron-fluid">
	  <div class="container text-white text-center">
	    <h1 class="display-4">Bismillah</h1>
 	    <p class="lead">Selamat Datang di Home Page Web Python</p>
	  </div>
	</div>
	<div class="container marketing">

		<div><h1><u>ABOUT US</u></h1></div>
		<P></P><P></P>
        <!-- 3 foto about us -->
        <div class="row">
          <div class="col-lg-4">
            <img class="rounded-circle" src="{% static "img/fatih.jpg" %}" alt="Generic placeholder image" width="140" height="140">
            <h2>Ahmad Fatihin</h2>
            <h7>11170930000059</h7>
            <div class="content" style="text-align:left;">
          		<div class="description" style="width:150;">Sistem Informasi 2017 Kelas 3B</div>
          		<P></P>
          		<div class="description" style="width:150;">
            	
            <p><b>ADMIN1</b></p>
          </div>
        </div>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle" src="{% static "img/meow.jpg" %}" alt="Generic placeholder image" width="140" height="140">
            <h2>Meow</h2>
            <h7></h7>
            <p></p>
            <h7></h7>
            <p><b> ADMIN2</b></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle" src="{% static "img/meow2.jpg" %}" alt="Generic placeholder image" width="140" height="140">
            <h2>Meow2</h2>
            <h7></h7>
            <p></p>
            <h7></h7>
            <p><b>ADMIN3</b></p>
          </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->

	
	<script src="{% static "vendor/jquery/jquery.js" %}" type="text/javascript"></script>
	
	<script src="{% static "vendor/popper/popper.js" %}" type="text/javascript"></script>

	<script src="{% static "vendor/bootstrap/bootstrap.js" %}" type="text/javascript"></script>

	<script src="{% static "js/scrolling.js" %}" type="text/javascript"></script>
</body>
</html>

Web design Python dengan framework Django/templates/snippets/navbar.html
<nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
		<div class="container">
			<a class="navbar-brand" href="#">
				<img src="{%static "img/banner_home.png" 
	%}" alt="">
				<h1>My Blog</h1>
			</a>

			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item">
						<a class="nav-link" href="{% url "index" %}">
							Home
						</a>
					</li>

					<li class="nav-item">
						<a class="nav-link" href="{% url "blog:index" %}">
							Blog
						</a>
					</li>

					<li class="nav-item">
						<a class="nav-link" href="{% url "admin:index" %}">
							Admin
						</a>
					</li>
				</ul>
			</div>

		</div>
	</nav>

Web design Python dengan framework Django/templates/snippets/scripts.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="{% static "js/tinymce/tinymce.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/tinymce/custom.js" %}" ></script>

Web design Python dengan framework Django/templates/snippets/styles.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">